config/routes.rb
Rails.application.routes.draw do
  
#https://calm-castle-11120.herokuapp.com/

# git push heroku master
# If you're not developing on master deploy with:

# git push heroku your_branch_name:master
post 'users/lol', to: 'users#lol'

  post 'proposals/url', to: 'proposals#url'

  post 'proposals/hello', to: 'proposals#hello'

  post 'buckets/hello', to: 'buckets#hello'

  post 'users/newbucket', to: 'users#newbucket'

  get 'users/getuser', to: 'users#getuser'

  resources :users do 
  	resources :buckets
  	resources :proposals
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  belongs_to :user
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	
	has_many :proposals
	has_many :buckets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session


end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /buckets
  # GET /buckets.json
  def index
    @buckets = Bucket.all

    render json: @buckets
  end


  # GET /buckets/1
  # GET /buckets/1.json
  def show
  end

  # GET /buckets/new
  def new
    @bucket = Bucket.new
  end

  # GET /buckets/1/edit
  def edit
  end

  # POST /buckets
  # POST /buckets.json
  def create

    p params
    @bucket = Bucket.new(bucket_params)

    @bucket.save

    render json: @bucket
    # respond_to do |format|
    #   if @bucket.save
    #     format.html { redirect_to @bucket, notice: 'Bucket was successfully created.' }
    #     format.json { render :show, status: :created, location: @bucket }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @bucket.errors, status: :unprocessable_entity }
    #   end
    
  end

  # PATCH/PUT /buckets/1
  # PATCH/PUT /buckets/1.json
  def update
    respond_to do |format|
      if @bucket.update(bucket_params)
        format.html { redirect_to @bucket, notice: 'Bucket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bucket }
      else
        format.html { render :edit }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buckets/1
  # DELETE /buckets/1.json
  def destroy
    @bucket.destroy
    respond_to do |format|
      format.html { redirect_to buckets_url, notice: 'Bucket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bucket
      @bucket = Bucket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bucket_params
      params.require(:bucket).permit(:item, :user_id, :item, :monthly, :months)
    end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]
skip_before_action :verify_authenticity_token
  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all

    render json: @proposals
  end


def url
         p params

    key = 'SEM3770FE56767FEDC920DD0DE5EA0480975'
    secret = 'Y2VkNzlkODQwYTI5NjAxMjAxOTEwYTdhMmQwN2I5ODQ'

    sem3 = Semantics3::Products.new(key,secret)

    sem3.products_field("url", params[:url])
    productsHash = sem3.get_products()
    bigJson = productsHash.to_json

    p bigJson
 p "-------------------------------------"
 bigJson = productsHash.to_json

     priceString = productsHash["results"][0]["price"]
     imageString = productsHash["results"][0]["images"][0]
     nameString = productsHash["results"][0]["name"]

     prop = Proposal.new
     prop.item = nameString
     prop.imageString = imageString
     prop.price = priceString.to_f
     prop.monthly = prop.price / 8
     prop.monthly = 8
     prop.user_id = 1


prop.save

p prop

render json: prop
end
end


  

#  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /users
  # GET /users.json

  def lol
      p params["bucket"]

      thebuck = params["bucket"]

      bucket = Bucket.new(item: thebuck["item"], price: Float(thebuck["price"]), monthly: Float(thebuck["monthly"]), months: Float(thebuck["months"]), user_id: "1", imageString: thebuck["imageString"])
      bucket.save

      render json: bucket
  end

  def newBucket

  end


  def index
    @users = User.all
  end

  
  # GET /users/1
  # GET /users/1.json


  # def show
  #   @user = User.find(params[:id])

  #   render json: @user
  # end

  # # GET /users/new
  # def new

  #   p params
  #   # @user = User.new
  # end

  # # GET /users/1/edit
  # def edit
  # end

  # # POST /users
  # # POST /users.json
  # def create

  #   p params
  #   @user = User.new(first_name: params[:first_name])

  #   # respond_to do |format|
  #     if @user.save

  #       p "new user!"
        
  #       render json: {id: @user.id}
  #   #     # format.html { redirect_to @user, notice: 'User was successfully created.' }
  #        # render json: {message: "User created successfully"}
  #     else
  #       p "nope!"
  #   #     # format.html { render :new }
  #   #    # render.json { render json: @user.errors, status: :unprocessable_entity }
  #   #   end
  #   end
  # end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_user
  #     @user = User.find(params[:id])
  #   end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def user_params
  #     params.require(:user).permit(:first_name)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buckets/_form.html.erb
<%= form_with(model: bucket, local: true) do |form| %>
  <% if bucket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bucket.errors.count, "error") %> prohibited this bucket from being saved:</h2>

      <ul>
      <% bucket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item, id: :bucket_item %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :bucket_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buckets/edit.html.erb
<h1>Editing Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Show', @bucket %> |
<%= link_to 'Back', buckets_path %>

app/views/buckets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buckets</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buckets.each do |bucket| %>
      <tr>
        <td><%= bucket.item %></td>
        <td><%= bucket.user %></td>
        <td><%= link_to 'Show', bucket %></td>
        <td><%= link_to 'Edit', edit_bucket_path(bucket) %></td>
        <td><%= link_to 'Destroy', bucket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bucket', new_bucket_path %>

app/views/buckets/new.html.erb
<h1>New Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Back', buckets_path %>

app/views/buckets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @bucket.item %>
</p>

<p>
  <strong>User:</strong>
  <%= @bucket.user %>
</p>

<%= link_to 'Edit', edit_bucket_path(@bucket) %> |
<%= link_to 'Back', buckets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketBackend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proposals/_form.html.erb
<%= form_with(model: new_user_proposal, local: true) do |form| %>
  <% if proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

      <ul>
      <% proposal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item, id: :proposal_item %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :proposal_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing Proposal</h1>

<%= render 'form', proposal: @proposal %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proposals</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= proposal.item %></td>
        <td><%= proposal.user %></td>
        <td><%= link_to 'Show', user_proposal_path(proposal.user_id, proposal) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proposal', new_user_proposal_path %>

app/views/proposals/new.html.erb
<h1>New Proposal</h1>

<%= render 'form', proposal: @proposal %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @proposal.item %>
</p>

<p>
  <strong>User:</strong>
  <%= @proposal.user %>
</p>

<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>